name: update data and deploy

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - 'standalone'

jobs:
  update-course:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: standalone
      - uses: actions/setup-python@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: "Install crawler's dependencies"
        run: |
          conda install -c conda-forge scrapy
      
      - name: "Execute the crawler"
        working-directory: ./crawler
        run: |
          scrapy crawl courses -O ../course-data/1121-data.json
    
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
